export { Login } from './login'
export { Register } from './register'
export { Product } from './product'
export { Payment } from './payment'
export { Supplier } from './supplier'
export { MyOrders } from './myOrders'
export { Suppliers } from './suppliers'